site_name: OCI Registry As Storage
site_url: https://oras.land/
site_description: Tools and libraries to enable leveraging OCI registries for arbitrary artifacts
site_author: The ORAS Authors
repo_url: https://github.com/oras-project/oras
repo_name: oras-project/oras
edit_uri: ""
copyright: Copyright &copy; 2023 The ORAS Authors.<br>We are a Cloud Native Computing Foundation sandbox project.
extra_css:
  - assets/stylesheets/extra.css
plugins:
  - search
  - git-revision-date-localized

extra:
  social:
    - icon: cncf/cncf-icon-white
      link: https://www.cncf.io/
    - icon: fontawesome/solid/trademark
      link: https://www.linuxfoundation.org/trademark-usage/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/orasproject
    - icon: fontawesome/brands/github
      link: https://github.com/oras-project/
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - meta
  - pymdownx.emoji:
       emoji_index: !!python/name:materialx.emoji.twemoji
       emoji_generator: !!python/name:materialx.emoji.to_svg
       options:
         custom_icons:
           - docs/custom/.icons
theme:
  name: material
  logo: assets/images/oras.png
  favicon: assets/favicon.ico
  custom_dir: docs/custom/
  # there are for golang vanity imports
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
